### ISSUE TITLE
Кажется где-то не хватает асинхронности. [WinError 64] Указанное сетевое имя более недоступно

### ISSUE THREAD

**Issue by joden95** [Re-Diss/IcebergAppBot#3]
Select an action:

    1. Run claimer
    2. Get statistics
    3. Create sessions

> 1
08:34:34.60 | INFO | Searched sessions: 1.
08:34:34.60 | SUCCESS | Search available accounts: 1.
08:34:34.60 | INFO | Checking accounts for valid...
08:34:36.21 | SUCCESS | Valid accounts: 1; Invalid: 0
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 489, in finish_recv
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 64] Указанное сетевое имя более недоступно

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 841, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 493, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] Указанное сетевое имя более недоступно

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kis\IcebergAppBot\main.py", line 72, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kis\IcebergAppBot\main.py", line 68, in main
    await asyncio.gather(*tasks)
  File "C:\Users\kis\IcebergAppBot\utils\starter.py", line 24, in start
    await iceberg.change_status(task['id'], 'in_work')
  File "C:\Users\kis\IcebergAppBot\utils\iceberg.py", line 134, in change_status
    resp = await self.session.patch(f'https://0xiceberg.store/api/v1/web-app/tasks/task/{task_id}/', json=json_data, proxy=self.proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kis\IcebergAppBot\venv\Lib\site-packages\aiohttp\client.py", line 608, in _request
    await resp.start(conn)
  File "C:\Users\kis\IcebergAppBot\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kis\IcebergAppBot\venv\Lib\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] Указанное сетевое имя более недоступно
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001727F2B4AD0>

**Comment by Re-Diss** [comment]
Может быть несколько причин:
1. Не работал сервер айсберг
2. Не стабильный интернет
3. Firewall блокирует соединение

а другие скрипты на ботов запускаются?

**Comment by joden95** [comment]
Все скрипты работают в том числе и твой на "TimeFarmCryptoBot" с 5 сессиями, а вот именно этот не работает. Пробовал 10 часов назад. Потом 5 часов назад. Потом снес полностью все и с нуля установил, на текущий момент все также - ошибка

**Comment by Re-Diss** [comment]
странно, посмотрю сегодня у себя на винде, потому что у меня на линукс и мак все работает

**Comment by Re-Diss** [comment]
@joden95 а ты с прокси запускаешь?

**Comment by joden95** [comment]
@Re-Diss  нет

**Comment by Re-Diss** [comment]
> @Re-Diss нет

проверил я на винде, все запустилось. Даже не знаю чем помочь, видимо что-то на твоей стороне блокирует подключение к серверу https://0xiceberg.store/api

**Comment by joden95** [comment]
Ну я проверил на нескольких компах. Удается запустить только единственный акаунт по твоему скрипту. Все остальные сессии летят с ошибкой "aiohttp.client_exceptions.ClientOSError: [WinError 64] Указанное сетевое имя более недоступно".
При этом все остальные скрипты от 5 других людей работают и даже твой на "TimeFarmCryptoBot" работает со всеми сессиями, а вот скрипт на "IcebergAppBot" работает только с одним единственным аккаунтом/сессией
