### ISSUE TITLE
 Retrying "updates.GetDifference"

### ISSUE THREAD

**Issue by qwerty123-noname** [Re-Diss/IcebergAppBot#4]
После того как собрались все аккаунты не уходит полностью в сон, а выдаёт ошибку 

socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
[10] Retrying "updates.GetDifference" due to: Connection lost
socket.send() raised exception.
Task exception was never retrieved
future: <Task finished name='Task-1725' coro=<Client.handle_updates() done, defined at C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\client.py:535> exception=OSError(ConnectionResetError('Connection lost'))>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\client.py", line 589, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 402, in invoke
    raise e from None
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 340, in send
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 337, in send
    await self.connection.send(payload)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\connection\connection.py", line 69, in send
    await self.protocol.send(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\connection\transport\tcp\tcp_abridged.py", line 38, in send
    await super().send(
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\connection\transport\tcp\tcp.py", line 104, in send
    raise OSError(e)
OSError: Connection lost

**Comment by Re-Diss** [comment]
еще репродюсится?
может в тот момент сервер не отвечал

**Comment by qwerty123-noname** [comment]
Да, всё окей, через время перезапускается и начаинает новый сбор

**Comment by Re-Diss** [comment]
doesn't reproduce anymore
